use serde::{Serialize, Deserialize};
use crate::schema::downloads; // refers to the schema file generated by diesel


#[derive(Queryable, Serialize, Deserialize, Debug, Clone)]
pub struct DownloadItem {
    pub id: i32,
    pub url: String,
    pub directory: String,
    pub format: String,
    pub quality: String,
    pub quality_label: String,
    pub status: String,
    pub title: Option<String>,
    pub file_name: Option<String>,
    pub thumbnail: Option<String>,
    pub length_seconds: Option<i32>,
    pub size_in_bytes: Option<i32>,
    pub current_chunk: Option<i32>,
    pub approx_duration_ms: Option<i32>,
}

#[derive(Insertable, Serialize, Deserialize, Debug, Clone)]
#[table_name = "downloads"]
pub struct NewDownloadItem {  // this struct will be use when inserting into the db, a struct can be Queryable and Insertable at the same time too. 
    pub url: String,
    pub directory: String,
    pub format: String,
    pub quality: String,
    pub quality_label: String,
}

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct UpdateDownloadItem {
    pub id: i32,
    pub title: String,
    pub file_name: String,
    pub thumbnail: String,
    pub length_seconds: i32,
    pub size_in_bytes: i32,
    pub approx_duration_ms: i32,
}