use serde::{Serialize, Deserialize};
use crate::schema::downloads; // refers to the schema file generated by diesel

#[derive(Queryable, Serialize, Deserialize, Debug, Clone)]
pub struct SmartMode {
    pub id: i32,
    pub enabled: bool,
    pub format: String,
    pub quality: String,
    pub directory: String,
}

#[derive(Serialize, Deserialize, Debug)]
pub struct UpdateSmartMode {
    pub id: i32,
    pub enabled: bool,
    pub format: String,
    pub quality: String,
    pub directory: String,
}

#[derive(Queryable, Serialize, Deserialize, Debug)]
pub struct GeneralPreferences {
    pub id: i32,
    pub prevent_system_sleep: bool,
    pub create_playlist_subdirectory: bool,
    pub numerate_playlists_files: bool,
    pub skip_playlists_duplicates: bool,
    pub remove_downloaded_items: bool,
}

#[derive(Serialize, Deserialize, Debug)]
pub struct UpdateGeneralPreferences {
    pub id: i32,
    pub prevent_system_sleep: bool,
    pub create_playlist_subdirectory: bool,
    pub numerate_playlists_files: bool,
    pub skip_playlists_duplicates: bool,
    pub remove_downloaded_items: bool,
}

#[derive(Queryable, Serialize, Deserialize, Debug)]
pub struct DownloadItem {
    pub id: i32,
    pub title: Option<String>,
    pub url: String,
    pub thumbnail: Option<String>,
    pub status: String,
    pub directory: String,
    pub length_seconds: i32,
    pub size_in_bytes: i32,
    pub current_chunk: Option<i32>,
    pub format: Option<String>,
    pub quality: Option<String>,
    pub quality_label: Option<String>,
    pub approx_duration_ms: Option<i32>,
}

#[derive(Insertable, Serialize, Debug, Clone)]
#[table_name = "downloads"]
pub struct NewDownloadItem {  // this struct will be use when inserting into the db, a struct can be Queryable and Insertable at the same time too. 
    pub url: String,
    pub directory: String,
}

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct UpdateDownloadItemInfo {
    pub id: i32,
    pub title: String,
    pub thumbnail: String,
    pub length_seconds: i32,
}

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct UpdateDownloadItemFullInfo {
    pub id: i32,
    pub size_in_bytes: i32,
    pub approx_duration_ms: i32,
    pub format: String,
    pub quality: String,
    pub quality_label: String,
}